Cadastrar gatinho
ignaciojvig/ong-manager-team1 pull request #26
Opened 2021-06-10 23:19 UTC by Graciliana

2021-06-10 23:46 UTC, ego-giova requested changes

2021-06-10 23:46 UTC, ego-giova commented on application/services/gatos.js
> +        console.log(gatos)
Remover console.log

2021-06-10 23:46 UTC, ego-giova commented on application/services/gatos.js
> +        console.log(erro)
Remover console.log

2021-06-10 23:57 UTC, Graciliana commented on application/services/gatos.js
> +        console.log(gatos)
Realizado as alteraçoes pontuadas

2021-06-10 23:57 UTC, Graciliana commented on application/services/gatos.js
> +        console.log(erro)
Solucionado a remoção dos console.log

2021-06-11 00:03 UTC, ego-giova approved these changes

2021-06-11 00:20 UTC, merged