Feature cadastro dog
ignaciojvig/ong-manager-team1 pull request #27
Opened 2021-06-10 23:32 UTC by luizaboralli

2021-06-10 23:38 UTC, ignaciojvig commented
@luizaboralli, é necessário antes de tudo fazer um merge para trazer o conteudo da master para sua branch, pois existe conteúdo novo nela.

2021-06-10 23:38 UTC, ignaciojvig commented
@luizaboralli também é necessario incluir seu endpoint no Swagger

2021-06-10 23:39 UTC, ignaciojvig commented on adapters/api/routes/dog.js
> +    /*  #swagger.parameters['post dog object'] = {
Pode remover o comentário pois aqui ele pode atrapalhar a legibilidade do código

2021-06-10 23:41 UTC, ignaciojvig commented on adapters/api/routes/dog.js
> +    /*  #swagger.parameters['put dog object'] = {
Aqui também

2021-06-11 22:41 UTC, ignaciojvig commented
@luizaboralli se puder, seria legal ter os models de dogs nos endpoints de POST e PUT do Swagger, pra conseguirmos testar eles com mais facilidade

2021-06-11 23:08 UTC, ignaciojvig commented
@luizaboralli, encontrei um probleminha rolando no POST.
Conforme conversamos, aparenta ser devido a uma discrepancia de campos entre o model de Dogs e a Migration de Dogs
Log do POST via Swagger abaixo:
`
ValidationError [SequelizeValidationError]: notNull Violation: Dog.status cannot be null
    at InstanceValidator._validate (C:\Users\vntjoig\Projects\WomenCanCode\ong-manager-team1\node_modules\sequelize\lib\instance-validator.js:78:13)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async InstanceValidator._validateAndRunHooks (C:\Users\vntjoig\Projects\WomenCanCode\ong-manager-team1\node_modules\sequelize\lib\instance-validator.js:111:7)
    at async InstanceValidator.validate (C:\Users\vntjoig\Projects\WomenCanCode\ong-manager-team1\node_modules\sequelize\lib\instance-validator.js:93:12)
    at async Dog.save (C:\Users\vntjoig\Projects\WomenCanCode\ong-manager-team1\node_modules\sequelize\lib\model.js:3877:7)
    at async Function.create (C:\Users\vntjoig\Projects\WomenCanCode\ong-manager-team1\node_modules\sequelize\lib\model.js:2207:12)
    at async Object.exports.register (C:\Users\vntjoig\Projects\WomenCanCode\ong-manager-team1\application\services\dog.js:5:20)
    at async Object.exports.post (C:\Users\vntjoig\Projects\WomenCanCode\ong-manager-team1\adapters\controllers\dog.js:4:18)
    at async C:\Users\vntjoig\Projects\WomenCanCode\ong-manager-team1\adapters\api\routes\dog.js:17:22 {
  errors: [
    ValidationErrorItem {
      message: 'Dog.status cannot be null',
      type: 'notNull Violation',
      path: 'status',
      value: null,
      origin: 'CORE',
      instance: [Dog],
      validatorKey: 'is_null',
      validatorName: null,
      validatorArgs: []
    }
  ]
}
C:\Users\vntjoig\Projects\WomenCanCode\ong-manager-team1\application\services\dog.js:9
    const error = new Error('An error ocurred while creating a dog');
                  ^

Error: An error ocurred while creating a dog
    at Object.exports.register (C:\Users\vntjoig\Projects\WomenCanCode\ong-manager-team1\application\services\dog.js:9:19)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async Object.exports.post (C:\Users\vntjoig\Projects\WomenCanCode\ong-manager-team1\adapters\controllers\dog.js:4:18)
    at async C:\Users\vntjoig\Projects\WomenCanCode\ong-manager-team1\adapters\api\routes\dog.js:17:22 {
  statusCode: 500
}
`

2021-06-12 14:10 UTC, ego-giova requested changes

2021-06-12 14:10 UTC, ego-giova commented on adapters/api/routes/dog.js
> +
Adicionar os comentários do Swagger igual fizemos para o Vet;

2021-06-12 14:10 UTC, ego-giova commented on adapters/api/routes/dog.js
> +
Adicionar os comentários do Swagger igual fizemos para o Vet;

2021-06-12 14:30 UTC, ego-giova approved these changes

2021-06-12 14:30 UTC, merged